### ISSUE TITLE
[FEATURE]Tooltipが画面外にはみ出さないようにする

### ISSUE THREAD

**Issue by nishio** [takahiroanno2024/anno-broadlistening#13]
<img width="841" alt="image" src="https://github.com/user-attachments/assets/b66ff621-1586-493b-b2e6-fcac486f8ddc" />

画面端に近い点をホバーした時にTooltipが画面外にはみ出して読めない。気づいたのでメモしておく。解決方法は思いついてない。

**Comment by nanocloudx** [comment]
Fixed #25
