### ISSUE TITLE
[BUG]TypeError: Client.__init__() got an unexpected keyword argument 'proxies'

### ISSUE THREAD

**Issue by nishio** [takahiroanno2024/anno-broadlistening#43]
### 概要

`TypeError: Client.__init__() got an unexpected keyword argument 'proxies'`

Devin環境で発生する。

### 再現手順

1. Devin環境
2. pyenv local 3.10
3. python -mvenv venv
4. pip install -r requirements.txt

### スクリーンショット・ログ

https://app.devin.ai/sessions/fa801489c6d64c8c821943a3a592854c?ts=1735325279903

### その他

こちらでいじる前に心当たりがあるか @nasuka さんに確認したい

**Comment by nishio** [comment]
from Devin
## OpenAIクライアントの互換性の問題

### 問題の概要
- エラー: `TypeError: Client.__init__() got an unexpected keyword argument 'proxies'`
- 発生箇所: Python分析パイプラインの実行時
- 影響: OpenAIのEmbeddings生成が失敗する

### 原因
1. パッケージのバージョンの不一致
   - openai: v1.52.2
   - langchain: v0.3.4
   - langchain-openai: v0.2.3
   - langchain-community: v0.3.3

2. 互換性の問題
   - langchain_communityパッケージのOpenAIEmbeddingsクラスが、新しいOpenAIクライアント（v1.52.2）と互換性がない
   - 具体的には、古いバージョンで使用されていた'proxies'パラメータを渡そうとしている

### 環境依存性
- 一部の環境では問題が発生せず、他の環境で発生する
- 考えられる要因：
  1. プロキシ設定の有無
  2. OpenAIクライアントのバージョンの違い
  3. langchainパッケージのバージョンの違い

### 対応案
1. 短期的な対応
   - OpenAIクライアントのバージョンを固定（例：v1.51.0）
   - プロキシ設定を環境変数で制御

2. 長期的な対応
   - langchain_communityパッケージの更新を待つ
   - OpenAIクライアントの新しいバージョンに対応したコードに修正

**Comment by nasuka** [comment]
@nishio 
こちらですが、devin環境で実行した際はpackageアップデートがなかったのでこちらのrepoのpython環境を使っていたんですが、新規に環境を構築したところ私の方でもエラーが再現しました。

https://github.com/takahiroanno2024/anno-broadlistening/pull/44
取り急ぎopenaiのパッケージをアップデートするとエラーが解消されました。package周りは直近いじっていないので、恐らく依存しているpackageがアップデートされたことで不整合が起きたのかと思います（が、エラーの原因の詳細は究明出来ていないです

**Comment by nishio** [comment]
ありがとうこざいます！以降あたらしいrequirements.txtでセットアップしますね
