### ISSUE TITLE
[FEATURE]全画面地図上で選択した属性をハイライトできるようにする

### ISSUE THREAD

**Issue by nasuka** [takahiroanno2024/anno-broadlistening#9]
### 背景
* 収集元のデータソースや、特定の属性（e.g. 年齢）情報に基づいてデータの分布を確認したい
  * 参考: https://scrapbox.io/nishio/Talk_to_the_City%E3%81%A8%E5%B1%9E%E6%80%A7%E3%81%AE%E6%8E%9B%E3%81%91%E5%90%88%E3%82%8F%E3%81%9B%E5%88%86%E6%9E%90

### 提案内容
* 全画面地図上で属性を選択できるようにし、選択された属性のデータ点をハイライトする

**Comment by nishio** [comment]
UI側はできている、実際の大規模データで属性付きのものをもらって試したい

**Comment by nishio** [comment]
[FEATURE]実験用大規模データセットを作る · Issue #28

**Comment by nishio** [comment]
動いているので一旦closeとしよう
